name: Lint

on:
  pull_request:
    paths:
      - src/*
  push:
    paths:
      - src/*

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hallee/eslint-action@master
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
